### ISSUE TITLE
MEDIUM - Register Page - Invalid full name still leads to successful registration

### ISSUE THREAD

**Issue by OneCodeMan** [behdadkha/ToeFX#10]
# Summary
User can register with an invalid full name. They should not be able to. 
Names should not contain numbers or special symbols (except for maybe `-`)

# Environment
Platform: Desktop
OS: Mac
Browser: Chrome

# Steps to Reproduce
1. Go to `localhost:3000/signup`
2. Enter a valid, non-existing email address, a valid password, and a valid age.
3. Enter a non-valid name (i.e. `1234`) in the `Full Name` field
4. Click `Create Account`
5. Observe successful creation of account despite invalid name.

![FullNameInvalid](https://user-images.githubusercontent.com/15069287/109087017-a8b03380-76da-11eb-84a0-70d3cc14f65f.png)

**Comment by behdadkha** [comment]
fixed!
