### ISSUE TITLE
MEDIUM - Register Page - Invalid age still leads to successful registration (please read NOTES below)

### ISSUE THREAD

**Issue by OneCodeMan** [behdadkha/ToeFX#11]
# Summary
User can successfully register with an invalid age (negative numbers).

# Environment
Platform: Desktop
OS: Mac
Browser: Chrome

# Steps to Reproduce
1. Go to `localhost:3000/signup`
2. Enter a valid, non-existing email address, a valid password, and a valid full name.
3. Enter a non-valid age (i.e. `-25`)
4. Click `Create Account`
5. Observe successful creation of account despite invalid age.

![NegativeAgeValid](https://user-images.githubusercontent.com/15069287/109087216-165c5f80-76db-11eb-8d1e-c37ed92e1623.png)

# Notes
- Negative age inputs and inputs over 100 lead to successful registration.
- Float inputs seem to not lead to successful registration, BUT no UI error message.

**Comment by Skeli789** [comment]
Fixed. Replaced with birthday input
