### ISSUE TITLE
MEDIUM - Upload Page - Uploading image for either foot, and then clicking on either tab (does not matter which foot user is on) removes uploaded image

### ISSUE THREAD

**Issue by OneCodeMan** [behdadkha/ToeFX#12]
# Summary
Uploading image for left foot, clicking on right foot tab, then clicking back on left foot tab removes the image being uploaded

NOTE: This happens even when you click the same tab you're on.

# Environment
Platform: Desktop
OS: Mac
Browser: Chrome

# Preconditions
1. Sign in as a user

Sample credentials: `bread@butter.com` // `Password1234`

# Steps to Reproduce
1. Go to `localhost:3000/upload`
2. Choose Left Foot tab
3. Click 'Upload'
4. Upload an image (you don't have to wait for it to finish uploading)
<img width="1175" alt="Bildschirmfoto 2021-02-24 um 20 07 41" src="https://user-images.githubusercontent.com/15069287/109088079-b6ff4f00-76dc-11eb-9615-6bfea55dbcca.png">

5. Click on the Right Foot tab
<img width="953" alt="Bildschirmfoto 2021-02-24 um 20 12 58" src="https://user-images.githubusercontent.com/15069287/109088085-bb2b6c80-76dc-11eb-85f5-80bff4011f2e.png">

6. Click again on the Left Foot tab
7. Observe that initial entry for Left Foot data from step 4 is gone.

<img width="933" alt="Bildschirmfoto 2021-02-24 um 20 13 01" src="https://user-images.githubusercontent.com/15069287/109088100-c2527a80-76dc-11eb-8b56-20b7d0b345d8.png">

**Comment by Skeli789** [comment]
Apparently, this is intentional. More detail may still be needed to make sure the user knows this.
