### ISSUE TITLE
HIGH: No Notice if Image Unrecognized

### ISSUE THREAD

**Issue by SEsseltine** [behdadkha/ToeFX#14]
### Bug Description
A user is not notified if an image could not be processed or if no toes could be found in the image.

**Severity:** HIGH

### Recreation Steps

Logged-In any valid user:
1. From the Dashboard click upload image
2. Select Left foot
3. Click the Upload button
4. Select an image that a toe cannot be recognized (image 12 from server's images/regular/12.png was used)

### Environment
**Browser:** Google Chrome

### Expected Behaviour
A warning message should notify the user that not toes could be found in the image.

### Actual Behaviour 
The user is not notified or prompted that toe identification failed.

**Comment by Skeli789** [comment]
Fixed
