### ISSUE TITLE
HIGH: User Can Set Invalid Password

### ISSUE THREAD

**Issue by SEsseltine** [behdadkha/ToeFX#16]
### Bug Description
Using the reset password option, a user can set an invalid password for themself.

**Severity:** HIGH

### Recreation Steps

From the dashboard of a logged-in user:
1. Click My Account
2. Click the Reset Password button
3. Enter the users current password
4. Enter an invalid password as is described on the signup page (e.g. password) in the New Password field
5. Re-enter the password used in Step 4 in the Confirm New Password field
6. Click the Submit button

### Environment
**Browser:** Google Chrome

### Expected Behaviour
The user is unable to set an invalid password.

### Actual Behaviour 
The user is able to set an invalid password.

**Comment by Behzadkha** [comment]
Fixed.
