### ISSUE TITLE
Upload page stuck on "Processing your image"

### ISSUE THREAD

**Issue by ipa-1** [behdadkha/ToeFX#18]
**Description:** Upload page stuck on "Processing your image", there are no error messages, there are no messages at all, or indication of what the application is doing

**Severity:** medium

**Environment:** 
OS Name: Microsoft Windows 10 Education  
OS Version: 10.0.19041 Build 19041  
System Manufacturer: Micro-Start International Co., Ltd  
System Model: MS-7C02  
System Type: x64-based PC  
Processor: AMD Ryzen 5 3600X 6-core Processor  
Internet Browser: Google Chrome  
Battery state: Desktop, is always plugged in  
Screen Orientation: The browser is full screen  
Application version: Testable artifact 

**Reproduction steps:** 
1. Click on Dashboard.
2. Click "+ Upload Image".
3. Click right foot option. (Same thing with left foot option)
4. Click "Upload".
5. Click image

**Expected result:**
Page has an error saying: "Processing time out", indicating that there is something wrong with the application, or an error saying "Invalid image", or some indication of how much longer it will take to process the image.

**Actual result:**
Page is stuck on processing, where the screen looks like
![image](https://user-images.githubusercontent.com/28264369/109231264-3bf96f80-7794-11eb-85b0-d52b88987fb8.png)

**Reproducibility Rate:** Consistent

**Comment by Skeli789** [comment]
Do you have the command line output for this bug? If you're using a local installation (and not docker), it could be because the Python script is failing due to modules that were not set up correctly.

**Comment by behdadkha** [comment]
fixed! It will display no toe detected if the AI can't find any toes or if the python script crashes.
