### ISSUE TITLE
Two toes are always highlighted when you go to dashboard

### ISSUE THREAD

**Issue by ipa-1** [behdadkha/ToeFX#19]
**Description:** When you log in, and go to dashboard, you see that two toes are highlighted. It is always the same two toes. It is not explained why the two toes are highlighted. There is no error shown either.

**Severity:** medium

**Environment:** 
OS Name: Microsoft Windows 10 Education  
OS Version: 10.0.19041 Build 19041  
System Manufacturer: Micro-Start International Co., Ltd  
System Model: MS-7C02  
System Type: x64-based PC  
Processor: AMD Ryzen 5 3600X 6-core Processor  
Internet Browser: Google Chrome  
Battery state: Desktop, is always plugged in  
Screen Orientation: The browser is full screen  
Application version: Testable artifact  

**Reproduction steps:** 
1. Log in.
2. Go to dashboard

**Expected result:**
No toes are highlighted on the page.

**Actual result:**
You see that two toes are highlighted. 

Left foot option:
![image](https://user-images.githubusercontent.com/28264369/109232274-0ce3fd80-7796-11eb-8cbd-61d77a81b331.png)

Right foot option:
![image](https://user-images.githubusercontent.com/28264369/109232322-29803580-7796-11eb-81d9-911e4c49438d.png)

**Reproducibility Rate:** Consistent

**Comment by Skeli789** [comment]
Those are just the two toes selected by default. #73 is a more accurate representation of what an issue here is (this two-toe selection can't be recreated).
