### ISSUE TITLE
Suggestion: Have a progress bar for after the image is uploaded

### ISSUE THREAD

**Issue by ipa-1** [behdadkha/ToeFX#21]
**Description:** After uploading an image, nothing happens. It could confuse the user, since the user does not know if the application successfully accepted the image, or if it is stuck processing, or if the program has reached an error, or if it is just still processing. If there was a progress bar to indicate amount of time life (Assuming the processing takes a long duration of time), then the user would know to wait.

**Severity:** low 
 
**Environment:** 
OS Name: Microsoft Windows 10 Education  
OS Version: 10.0.19041 Build 19041  
System Manufacturer: Micro-Start International Co., Ltd  
System Model: MS-7C02  
System Type: x64-based PC  
Processor: AMD Ryzen 5 3600X 6-core Processor  
Internet Browser: Google Chrome  
Battery state: Desktop, is always plugged in  
Screen Orientation: The browser is full screen  
Application version: Testable artifact

**Comment by Skeli789** [comment]
The image uploaded is displayed with the label ``Processing your image...`` to indicate that something *is* happening. Unfortunately, it is impossible to create a progress bar for this, as there is no estimate for how long the processing will take.
