### ISSUE TITLE
Toenail Preview too closeup to identify toe

### ISSUE THREAD

**Issue by connorhewick** [behdadkha/ToeFX#22]
When foot image is processed the toenail preview windows are too closeup to easily identify the toe.
![Screen Shot 2021-02-25 at 8 04 57 PM](https://user-images.githubusercontent.com/37413894/109240235-204a9500-77a5-11eb-97a5-f65d5e076e30.png)

**Comment by Skeli789** [comment]
Fixed with coloured boundaries.
