### ISSUE TITLE
Signup error's don't refresh after hitting submit a second time

### ISSUE THREAD

**Issue by nikhail-singh** [behdadkha/ToeFX#26]
**description** previous error messages aren't cleared if user makes a multiple on the signup screen for example the feedback: "please fill in all fields" is still here from this screenshot

![image](https://user-images.githubusercontent.com/35268769/109254936-061eb000-77c1-11eb-9d95-4e249336ff09.png)

in this screenshot

![image](https://user-images.githubusercontent.com/35268769/109255068-441bd400-77c1-11eb-9c0c-23716800d938.png)
### Browser and system
Google Chrome on Windows 10

## Steps to Reproduce:
1. open the signup page
2. enter incorrect information leading to an error
3. fix the first error but make a new error
4. old error message still shows
5. (see screenshots above for an example)

**Comment by Skeli789** [comment]
Fixed
