### ISSUE TITLE
Uploading an image of a hand works for either foot

### ISSUE THREAD

**Issue by nikhail-singh** [behdadkha/ToeFX#28]
### Description
When going to upload a photo of a foot, you can upload a photo of a hand and it will work as if the hand was a foot and ask a user to select "toe nails"
### Browser and System
Google Chrome on Windows 10
### Steps to recreate
1. go to the upload page
2. select either left/right foot
3. click upload
4. select an image of a hand

**Comment by Skeli789** [comment]
Duplicate of #13
