### ISSUE TITLE
[My Account] Two right scrollbars on the My Account page

### ISSUE THREAD

**Issue by FangY2019** [behdadkha/ToeFX#29]
If more than 5 images are saved in my account, there are two right scrollbars in the My Account page. 
The mouse does not work well with the two scrollbars by scrolling.

## Environment

Device: ASUS Laptop
OS: Windows 10
Browser: Google Chrome

## Steps to Reproduce

    1. Upload more than 5 images
    2. Go to My Account
	
## Expected Result

There should be one right scrollbar in the same page.

## Actual Result

There are two scrollbars when there are more than five images in the account.

## Screenshot

![toe3](https://user-images.githubusercontent.com/54195303/109262726-0c685880-77d0-11eb-9349-7c42c332d8d4.PNG)

## Severity
LOW

**Comment by Skeli789** [comment]
Fixed
