### ISSUE TITLE
[My Account] 0% fungal coverage for an infected toenail

### ISSUE THREAD

**Issue by FangY2019** [behdadkha/ToeFX#31]
When I upload an infected toenail, the fungal coverage returns to be 0%.

## Environment

Device: ASUS Laptop
OS: Windows 10
Browser: Google Chrome

## Steps to Reproduce

    1. Upload Image
    2. Choose Left foot
    3. Upload a foot image
    4. Keep the infected toenail previews
    5. Click Dashboard
    6. Go to My Account
	
	
## Expected Result

There should be more than 0% for the infected toenail.

## Actual Result

0% fungal coverage for an infected toenail.

## Screenshot

![toe8](https://user-images.githubusercontent.com/54195303/109311118-63435180-7813-11eb-9f6a-a0a4e2233c39.PNG)

## Severity
HIGH

**Comment by Skeli789** [comment]
Duplicate of #3
