### ISSUE TITLE
[Dashboard] There is only one point in the graph after uploading three big toe images in the same day

### ISSUE THREAD

**Issue by FangY2019** [behdadkha/ToeFX#32]
When I upload upload three image for big toe in the same day, only the last toenail details will be shown in the graph

## Environment

Device: ASUS Laptop
OS: Windows 10
Browser: Google Chrome

## Steps to Reproduce

1. Upload Image
2. Choose Left foot
3. Upload a foot image
4. Keep the the first toenail as big toe
5. Repeat step 3 and 4 for two times
6. Go back to Dashboard
7. Click on the graph points
	
	
## Expected Result

There should be three points in the graph.

## Actual Result

There is one point for the last uploaded toenail.

## Screenshot
![toe9](https://user-images.githubusercontent.com/54195303/109313510-4f4d1f00-7816-11eb-9463-4e29ede8b08a.PNG)

## Severity
Medium

**Comment by behdadkha** [comment]
The new AI model will most likely fix this issue as there will be a correct fungal coverage calculation for toes. In case of a toe with multiple image with the same fungal coverage, uploaded on the same day, only the most recent picture will be displayed.
