### ISSUE TITLE
[Upload Image] The orders of toenail preview are different for the same foot image

### ISSUE THREAD

**Issue by FangY2019** [behdadkha/ToeFX#33]
For the same foot image, the order of the toenail preview is random, which make it harder to identify the toes when the toenail preview is not clear. 

## Environment

Device: ASUS Laptop
OS: Windows 10
Browser: Google Chrome

## Steps to Reproduce

1. Upload Image
2. Choose Left foot
3. Upload a foot image
4. Choose Left foot 
5. Upload the same foot image

	
## Expected Result

There order of the toenail preview should be the same for the same foot image

## Actual Result

The order of the toenail preview is random

## Screenshot
![toe6](https://user-images.githubusercontent.com/54195303/109315196-48271080-7818-11eb-9659-fbe557678de8.PNG)
![toe5](https://user-images.githubusercontent.com/54195303/109315168-3ba2b800-7818-11eb-96a4-170a23c8b91d.PNG)

## Severity
LOW

**Comment by Skeli789** [comment]
Fixed
