### ISSUE TITLE
Strange behaviour after Sign Up form submitted

### ISSUE THREAD

**Issue by Sujan-Kandeepan** [behdadkha/ToeFX#38]
Steps to reproduce:
1. Select Sign Up from the initial screen
2. Complete the questionnaire with valid information
3. Submit the form to create a new account

Expected behaviour: should be logged in after submitting the form, just as if the user logged in with an existing account.

Actual behaviour: redirected to the Login page and asked to re-enter credentials already given, toggle in the corner leads back to the same Login page when clicked instead of the expected Sign Up page, as shown below:
![image](https://user-images.githubusercontent.com/25377268/109364597-2603b180-785d-11eb-9243-22e59e787491.png)

Severity: Medium
Priority: Medium

**Comment by Skeli789** [comment]
Email verification has just been included, so the user will need to login again after they verify their account.
