### ISSUE TITLE
Missing image upload button after invalid file given

### ISSUE THREAD

**Issue by Sujan-Kandeepan** [behdadkha/ToeFX#39]
Steps to reproduce:
1. Navigate to the `/upload` page route where expected to upload photos of toes.
2. Click Upload to bring up the file picker.
3. Change the allowed filename extensions to `All files (*.*)`
![image](https://user-images.githubusercontent.com/25377268/109365590-8c89cf00-785f-11eb-8d0e-de17727d1770.png)
4. Select a random file with an invalid extension, eg. PDF file as used when this issue was observed.
5. Submit the file (error message should appear).

Expected behaviour: The Upload button still made visible to retry the image upload using a file with a valid file type.

Actual behaviour: The Upload button is gone at this stage with nothing else to click aside from the error message and the foot selector. The Upload button does appear when the foot selector is clicked again, but not immediately after the failed upload.

![image](https://user-images.githubusercontent.com/25377268/109365550-71b75a80-785f-11eb-9844-adaa3ddeb199.png)

Platform: Windows
Browser: Microsoft Edge (Chromium-based)

Severity: Medium
Priority: Medium

**Comment by Skeli789** [comment]
Fixed
