### ISSUE TITLE
No feedback given when same toe selected twice

### ISSUE THREAD

**Issue by Sujan-Kandeepan** [behdadkha/ToeFX#40]
Steps to reproduce:
1. Upload a valid image displaying multiple identifiable toes.
2. Select Keep on one of the toes identified.
3. Specify which toe it is using the selector.
4. Click Save for that toe and wait for it to finish processing.
5. Select Keep on another toe.
6. Specify this toe to have the same 1-5 index as the previous toe.

Expected behaviour: Feedback of any type to indicate that the toe cannot be the same as the other toes.

Actual behaviour: no visual feedback as the toe remains unselected, and the user must correct their own error without help by selecting a different toe which will be highlighted only if it is valid.

Severity: Medium
Priority: Medium

**Comment by Skeli789** [comment]
Fixed
