### ISSUE TITLE
Deleting right toe image leads back to list of left toe images

### ISSUE THREAD

**Issue by Sujan-Kandeepan** [behdadkha/ToeFX#41]
When deleting multiple images of right toes in the Dashboard, the automatic page refresh leads back to the list of left toes as the selection of Left Foot vs. Right Foot is not preserved. This slows down the common use case of deleting the entire set of images given for the right foot on a given day, as the user is expected to re-select Right Foot on every refresh of the images list.

Potential solutions to improve the user experience:
- Navigate back to the previously selected option between Left Foot and Right Foot after the refresh.
- Group images uploaded at the same time using the same source image so they can also be deleted together.
- Allow multiple images to be deleted at the same time, perhaps using checkboxes akin to most file explorers.

Severity: Low
Priority: Low

**Comment by Skeli789** [comment]
Fixed
