### ISSUE TITLE
Header logo links to static path

### ISSUE THREAD

**Issue by Sujan-Kandeepan** [behdadkha/ToeFX#44]
When logged out, the ToeFX header logo redirects to https://www.toefx.com/ even with the app being tested at http://localhost:3000/. This implies that the redirect location is static and would be broken if the website permanently moved.

Expected behaviour: header logo should redirect to the `/` route within the same domain to remain wherever the site is deployed.

Severity: Low
Priority: Low

**Comment by Sujan-Kandeepan** [comment]
If the intended behaviour is indeed to lead back to the ToeFX home page instead of to the home page of this application, it may be best to replace the text with the actual logo used on the ToeFX home page to keep it consistent.

**Comment by Skeli789** [comment]
Fixed. It now just redirects the home page.
