### ISSUE TITLE
Stuck while processing broken image

### ISSUE THREAD

**Issue by Sujan-Kandeepan** [behdadkha/ToeFX#45]
Steps to reproduce:
1. Create a plaintext file and populate the file with content in text format instead of binary.
2. Rename the text file with any of the expected filename extensions for images (`.png` used here).
3. Upload that file, following the usual procedure within the `/upload` page route.

Expected behaviour: some type of error if the image could not be parsed in the back end, or rejecting the image if its contents cannot be parsed as a binary image file with the format given by the extension (the former option might be more reasonable).

Actual behaviour: application gets stuck without a message displayed to the user, back-end errors or timeouts not reported.

![image](https://user-images.githubusercontent.com/25377268/109373553-7a1e8e00-787d-11eb-9b0a-6f277b560303.png)

Severity: High
Priority: High

**Comment by behdadkha** [comment]
It will display, no toe detected if the AI can't find any toes.

**Comment by Skeli789** [comment]
Fixed.
