### ISSUE TITLE
Home page accessible only through Reset Password page when logged in

### ISSUE THREAD

**Issue by Sujan-Kandeepan** [behdadkha/ToeFX#46]
There seem to be two distinct ways that the user can access the Home page at any point:
- Ensure that they are logged out and the header appears which has a button to navigate home.
- Navigate to Dashboard -> My Account -> Reset Password -> Home to display home page while logged in.

The header bar does seem to behave differently when the user is logged in and this implies that it is expected to be able to see the Home page while logged in. The header bar remains hidden on most other pages, however, and it seems rather odd that the user is able to access the Home page just through one route, instead of always or never.

If the user is expected to have access to the Home page then the header should perhaps remain persistent or there can be another means of going home at any time. If the Home page is to remain hidden unless the user is logged out, the header should be hidden even in the Reset Password page. 

Severity: High
Priority: High

**Comment by Skeli789** [comment]
Fixed
