### ISSUE TITLE
Rendering issue with the sticky messenger button at the bottom right

### ISSUE THREAD

**Issue by robertjvardy** [behdadkha/ToeFX#47]
Issue:
- on the home page there seems to be an issue with the rendering of the sticky messenger button at the bottom right
- behind the message button there seems to be an element (with id: hubspot-messages-iframe-container) that seems to be out of place
- doesn't seem like good design and is confusing as the element looks like a navigation button
- see attached image

Steps to reproduce:
- run the application as suggested
- located the element in the bottom right corner of the landing page

priority: medium
severity: low

![image](https://user-images.githubusercontent.com/47096316/109425791-1c429100-79b8-11eb-89dd-3d996917b787.png)

**Comment by Skeli789** [comment]
Hi! I don't believe you're testing our application (toefx.com is the website of our client, and not what we developed)! Please follow the README to run it!
