### ISSUE TITLE
Scrolling on the Products page causes the UI to jump

### ISSUE THREAD

**Issue by robertjvardy** [behdadkha/ToeFX#48]
Steps to reproduce:
-  run the app as suggested on the readme
- navigate to the product page through the nav bar on the main menu
- slowly scroll to the bottom of the page

Results:
- expected: smooth transition
- actual: the UI jumps vertically, about half way down the page the header disappears and then reappears. Bad UX

**Comment by robertjvardy** [comment]
Note this actually happens on every page

**Comment by Skeli789** [comment]
Hi! Thank you for testing, but unfortunately, I don't believe you're testing our application! I believe you clicked on a link and were redirected to the website of our client, and not what we developed for them. Please follow the instructions in the provided documentation to access what we worked on (you should start by creating an account).
