### ISSUE TITLE
Research study pop up reappears on navigation to every page

### ISSUE THREAD

**Issue by robertjvardy** [behdadkha/ToeFX#49]
Steps to reproduce:
-  run the app as suggested on the readme
- note the Research popup
- navigate to any other UI page through the nav bar on the main menu

Results:
- expected: pop up should not reappear 
- actual: pop up reappears, and not just the first time, navigating back and forth to the same page will cause the pop up to re-render. EXTREMELY ANNOYING

Suggestion:
- use react-cookies found here: https://www.npmjs.com/package/react-cookie
- great and simple solution to track user session
- set a time window for which to show the pop-up again

![image](https://user-images.githubusercontent.com/47096316/109426281-c58a8680-79ba-11eb-8f77-1733399159f1.png)

**Comment by Skeli789** [comment]
Hi! Thank you for testing, but unfortunately, I don't believe you're testing our application! I believe you clicked on a link and were redirected to the website of our client, and not what we developed for them. Please follow the instructions in the provided documentation to access what we worked on (you should start by creating an account).
