### ISSUE TITLE
Age form field on sign up supports negative numbers

### ISSUE THREAD

**Issue by robertjvardy** [behdadkha/ToeFX#51]
Steps to reproduce:
- run app as indicated on the readme
- navigate to the sign up page
- enter a negative number for the form field: age

expected: throws error
actual: works fine and creates account

priority: medium
severity: low

![image](https://user-images.githubusercontent.com/47096316/109427026-79d9dc00-79be-11eb-97f0-4f1c8e2f61e5.png)

**Comment by Skeli789** [comment]
Duplicate of #11
