### ISSUE TITLE
If email address has been taken, form field email does not remove error state on value change

### ISSUE THREAD

**Issue by robertjvardy** [behdadkha/ToeFX#52]
Steps to reproduce:
- run app as indicated by the read me
- navigate to the sign up page
- create an account as instructed by the UI
- return to the sign up page
- enter the same email previously used
- note the error state of the email form field
- change the value of the email form field to a new unused email

expected: red error state is removed
actual: red error state persists and the form can be submitted even though it is shown to be in an error state

severity: low
priority: medium

![image](https://user-images.githubusercontent.com/47096316/109427268-8f033a80-79bf-11eb-884f-784a4c89af0a.png)

**Comment by Skeli789** [comment]
Fixed
