### ISSUE TITLE
Sign up form validates passwords of length 7

### ISSUE THREAD

**Issue by robertjvardy** [behdadkha/ToeFX#53]
Steps to reproduce:

- run app as indicated by the read me
- navigate to the sign up page
- fill out the form properly according to its instructions
- enter password and then confirm password: 123zxcA

expected: red error state and invalid form
actual: red error state not present and the form can be submitted

severity: high
priority: high

![image](https://user-images.githubusercontent.com/47096316/109427403-3e401180-79c0-11eb-9775-708e30566786.png)

**Comment by Behzadkha** [comment]
Fixed.
