### ISSUE TITLE
Accounts can be created that can't be signed in

### ISSUE THREAD

**Issue by robertjvardy** [behdadkha/ToeFX#54]
Steps to reproduce:

- run app as indicated by the read me
- navigate to the sign up page
- create an account with password: 123zxcA
- after redirection to the login page attempt to sign in with the users info

expected: should sign in
actual: error notification presented even though the account was created 

severity: high
priority: high

![image](https://user-images.githubusercontent.com/47096316/109427690-8ad81c80-79c1-11eb-823e-3869842a832b.png)

**Comment by Skeli789** [comment]
Fixed
