### ISSUE TITLE
No option to recover password before sign in

### ISSUE THREAD

**Issue by robertjvardy** [behdadkha/ToeFX#55]
Steps to reproduce:

-run app as indicated by the read me
-navigate to the sign up page
-create an account with password: 123zxcA
- after redirection to the login page attempt to sign in with the users info
- user is notified there is an error with the log in info

expected: should have the ability to recover/change password
actual: no option is presented even though the account was created

This essentially renders the email address used void as there exists no option to change the password even though the account was successfully created. You've created a deadlock for a given email

severity: high
priority: high

**Comment by Skeli789** [comment]
Fixed
