### ISSUE TITLE
No way to get back to the sign up page after creating an account 

### ISSUE THREAD

**Issue by robertjvardy** [behdadkha/ToeFX#56]
Steps to reproduce:

-run app as indicated by the read me
-navigate to the sign up page
-create an account as instructed

expected: nav bar on the login page should show sign up
actual: nav bar on the login page shows login, theres no way to get back to the sign up page

severity: medium
priority: high

![image](https://user-images.githubusercontent.com/47096316/109427964-d3440a00-79c2-11eb-8de7-654ae7ae233a.png)

**Comment by Skeli789** [comment]
Fixed
