### ISSUE TITLE
password needs to be hashed!

### ISSUE THREAD

**Issue by robertjvardy** [behdadkha/ToeFX#57]
Steps to reproduce:
- run app as indicated by the read me
- navigate to the sign up page
- create an account

The users password is being sent in plain text, that's a security risk

![image](https://user-images.githubusercontent.com/47096316/109428507-5a927d00-79c5-11eb-8e97-c9841574bd5c.png)

severity: high
priority: high

**Comment by behdadkha** [comment]
The app is hosted on Firebase with a valid ssl certificate.
