### ISSUE TITLE
NIT: Failed login results in 400 instead of 403

### ISSUE THREAD

**Issue by robertjvardy** [behdadkha/ToeFX#59]
Steps to reproduce:
- run app as instructed by the readme
- navigate to the login page
- attempt to log in with incorrect credentials 

expected: return 403 unauthorized
actual: response contains 400 status code

This is a best practice, not the end of the world.

severity: low
priority: low

![image](https://user-images.githubusercontent.com/47096316/109428984-87479400-79c7-11eb-956d-1c77144bdd80.png)

**Comment by Skeli789** [comment]
Fixed
