### ISSUE TITLE
Back end validations lacking

### ISSUE THREAD

**Issue by robertjvardy** [behdadkha/ToeFX#60]
Steps to reproduce:
- using postman (or any other tool of the like) submit a request to http://localhost:3001/signup with a body as follows:

{"name":" ","email":"ttttttttttttttttttttttest@test.com","password":" ","age":" "}

expected: should return an issue
result: returns 200

severity: high
priority: high

![image](https://user-images.githubusercontent.com/47096316/109429450-beb74000-79c9-11eb-95f9-1ed145ead469.png)

**Comment by behdadkha** [comment]
fixed!
