### ISSUE TITLE
AI interprets fingernails as toes

### ISSUE THREAD

**Issue by robertjvardy** [behdadkha/ToeFX#62]
Steps to reproduce:
- run the app as instructed in the readme
- create a user
- sign in via the login page
- click the upload button and upload an image of a hand

Expected: AI should recognize a hand is not a foot
Actual: fingernails recognized as toes

![image](https://user-images.githubusercontent.com/47096316/109907599-9e5cdf00-7c70-11eb-8594-e3ad7739cd40.png)

**Comment by Skeli789** [comment]
Duplicate of #13
