### ISSUE TITLE
Landing page footer not centered and has too much white space

### ISSUE THREAD

**Issue by Gabriel-Gebril** [behdadkha/ToeFX#64]
![image](https://user-images.githubusercontent.com/16761051/110039273-fa764080-7d0e-11eb-9c93-00892c9170c5.png)
The footer of the landing page should fill the screen and be centered.

Environment: Windows, Google Chrome
Steps to Reproduce

- Navigate to localhost:3000
- Scroll down to the footer
- The footer is biased to the right and doesn't cover the bottom.

**Comment by Skeli789** [comment]
Fixed
