### ISSUE TITLE
Create account button is an in active state even if a field is wrong

### ISSUE THREAD

**Issue by Gabriel-Gebril** [behdadkha/ToeFX#65]
When creating an account if you enter an invalid password the "Create Account" button is clickable but does nothing instead of highlighting where the problem is.

Environment: Windows, Google Chrome
Steps to Reproduce

- Navigate to account creation page
- Have at least one field be incorrect
- Clicking "Create Account" will not change focus or tell you what is wrong

![image](https://user-images.githubusercontent.com/16761051/110039763-ba638d80-7d0f-11eb-9fa1-78a05c24a36f.png)

**Comment by Skeli789** [comment]
Fixed
