### ISSUE TITLE
Clicking save in one dialogue says it's calculating fungal coverage in all dialogues

### ISSUE THREAD

**Issue by Gabriel-Gebril** [behdadkha/ToeFX#68]
After selecting which toe the image is for and hitting save all dialogues get the "calculating fungal percentage" block.

Environment: Windows, Google Chrome
Steps to Reproduce

- Upload an image with multiple toes exposed
- Click "save"
- All boxes will say "calculating fungal percentage"

**Comment by Gabriel-Gebril** [comment]
Environment: Windows, Google Chrome
Steps to Reproduce

-Upload an image with multiple toes exposed
- The dialogue that asks to select a toe select any toe
- All dialogues will change at the same time

**Comment by Skeli789** [comment]
Fixed
