### ISSUE TITLE
Clicking ToeFX on landing page leads to different home page

### ISSUE THREAD

**Issue by Gabriel-Gebril** [behdadkha/ToeFX#69]
Clicking on ToeFX in header should lead to the same home page, right now "Home" and ToeFX lead to 2 different URLs.

**Comment by Gabriel-Gebril** [comment]
Environment: Windows, Google Chrome
Steps to Reproduce

- Visit localhost:3000
-  Click "ToeFX" in upper left hand corner

**Comment by Skeli789** [comment]
Duplicate of #44
