### ISSUE TITLE
Signup age input field accepts extremely large age values

### ISSUE THREAD

**Issue by DavidHospital** [behdadkha/ToeFX#70]
![extremely_large_age_value_accepted](https://user-images.githubusercontent.com/19175976/110179002-53101100-7dd5-11eb-9e00-9edb655d333f.PNG)

After pressing "Create Account", the account is created sucessfully, even though age value is extremely large.

I would recommend asking for the user's date of birth instead of age, as their age will change over time.

**Comment by Skeli789** [comment]
Duplicate of #11
