### ISSUE TITLE
AI only recognizes a single toe after uploading stock photo of left foot

### ISSUE THREAD

**Issue by DavidHospital** [behdadkha/ToeFX#71]
When uploading a stock photo of a left foot after choosing the left foot option, the AI only recognizes one of five toes. Also, since the toe is quite zoomed in, it is difficult to tell which toe from the photo it is.

![only_one_toe](https://user-images.githubusercontent.com/19175976/110179927-e3028a80-7dd6-11eb-8ffc-2511a0d31ba6.PNG)

**Comment by behdadkha** [comment]
The recent update puts a colored box around the toe in the original image and draws a border with the same color around the extracted toe.
