### ISSUE TITLE
Foot on Dashboard page has 2 toes selected, however user cannot select multiple toes on their own

### ISSUE THREAD

**Issue by DavidHospital** [behdadkha/ToeFX#73]
On the Dashboard page, there are 2 selected toes on the foot component by default (big and index), however the user has no way to select more than one toe (other than all five by clicking on the foot), other than those two selected when first loading the landing page, or when switching between feet.

![multiple_toes](https://user-images.githubusercontent.com/19175976/110182936-c7e64980-7ddb-11eb-8d79-eeda2b28c4f0.PNG)

**Comment by behdadkha** [comment]
fixed!
