### ISSUE TITLE
Signup Age field accepts allows user to type the characters "e", "+", "-"

### ISSUE THREAD

**Issue by DavidHospital** [behdadkha/ToeFX#74]
The age field allows users to enter the characters "e", "+", and "-", presumably for numbers expressed in scientific notation (no other letters are accepted). When pressing "Create Account", user is shown "Please enter a number" (thankfully).

![e](https://user-images.githubusercontent.com/19175976/110186012-f1a26f00-7de1-11eb-81ce-63c94a09c698.PNG)

**Comment by Skeli789** [comment]
Fixed. Replaced with birthday input
