### ISSUE TITLE
No error message shown when given passwords don't match during signup

### ISSUE THREAD

**Issue by Sujan-Kandeepan** [behdadkha/ToeFX#76]
Steps to reproduce:
1. Navigate to the signup page at the `/signup` endpoint.
2. Enter valid/expected information for email, full name, and age.
3. Enter a new valid password and a different valid password as confirmation.

Expected behaviour: error message displayed to indicate that passwords entered do not match.

Actual behaviour: both password fields are highlighted red with no other indication why.

Severity: Medium
Priority: Medium

**Comment by Skeli789** [comment]
Fixed
