### ISSUE TITLE
Error messages not always cleared on login form

### ISSUE THREAD

**Issue by Sujan-Kandeepan** [behdadkha/ToeFX#77]
Steps to reproduce:
1. Navigate to the login form at the `/login` endpoint.
2. Enter an email address with no password. -> "Invalid Password"
3. Enter an incorrect password. -> "Please enter valid credentials."

Expected behaviour: "Invalid Password" message is cleared before "Please enter valid credentials." is displayed.

Actual behaviour: both error messages are displayed and the latter slightly overlaps with the label text below.

![image](https://user-images.githubusercontent.com/25377268/110197996-326ba980-7e1d-11eb-938d-a02b472e0dac.png)

Severity: Medium
Priority: Medium

**Comment by Skeli789** [comment]
Fixed
