### ISSUE TITLE
Image upload failing

### ISSUE THREAD

**Issue by Sujan-Kandeepan** [behdadkha/ToeFX#78]
Recent testing has resulted in the following error appearing whenever attempting to upload an image at the `/upload` endpoint:
```node
Error while attempting to move the image:
[Error: ENOENT: no such file or directory, open './images/60397c77c11e1500121339d3/15.jpg'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './images/60397c77c11e1500121339d3/15.jpg'
}
```

Currently testing with commit `63e8daf31e845c766c115d1eedc64b13894cc935` as instructed for external testing.

Severity: High
Priority: High

**Comment by Skeli789** [comment]
It could just be because the /upload endpoint isn't meant to be used like that.
@behdadkha @Behzadkha would know better, though.

**Comment by behdadkha** [comment]
fixed!
