### ISSUE TITLE
MEDIUM: Sign-Up Input Fields Overflow Container on Mobile

### ISSUE THREAD

**Issue by SEsseltine** [behdadkha/ToeFX#79]
### Bug Description
Input fields on the sign-up page overflow their container on mobile devices.

**Severity:** MEDIUM

### Recreation Steps
On a mobile device:
1. Navigate to the Sign-Up page

### Environment
**Browser:** Google Chrome
**Sim Device:** iPhone X

### Expected Behaviour
Fields should be contained in their container

### Actual Behaviour 
Fields overflow their container

### Supporting Images
![image](https://user-images.githubusercontent.com/16650214/110252609-3ea65280-7f54-11eb-8d0d-84801641473e.png)

**Comment by Skeli789** [comment]
Fixed
