### ISSUE TITLE
LOW - Login Page - Text overlap between form error messages and "email address" form label

### ISSUE THREAD

**Issue by OneCodeMan** [behdadkha/ToeFX#8]
# Summary
On the login page, at a desktop width of about 1159px, there is a text overlap between form error messages and form labels.

<img width="615" alt="Bildschirmfoto 2021-02-24 um 19 28 47" src="https://user-images.githubusercontent.com/15069287/109084837-87e5df00-76d6-11eb-818a-ea5a7422da4a.png">

# Environment
Platform: Desktop
OS: Mac
Browser: Chrome

# Steps to Reproduce
1. Go to `http://localhost:3000/login` without being logged in.
2. Enter `john@smith.ca` as email address (or an unregistered email)
3. Enter `xxx` as `password`
4. Click 'Login'

You should see this:
<img width="451" alt="Bildschirmfoto 2021-02-24 um 19 23 16" src="https://user-images.githubusercontent.com/15069287/109084415-c0d18400-76d5-11eb-9e15-d5327beb8054.png">

5. Empty out the password field like so:
<img width="442" alt="Bildschirmfoto 2021-02-24 um 19 25 48" src="https://user-images.githubusercontent.com/15069287/109084614-1ad24980-76d6-11eb-8b95-355b45467344.png">

6. Click `Login` again.

You should see this now:
<img width="448" alt="Bildschirmfoto 2021-02-24 um 19 26 11" src="https://user-images.githubusercontent.com/15069287/109084643-2887cf00-76d6-11eb-8520-f58ae15b60be.png">

7. Shrink the screen's width and observe the text "Invalid Password" overlapping with "Email address"
<img width="615" alt="Bildschirmfoto 2021-02-24 um 19 28 47" src="https://user-images.githubusercontent.com/15069287/109084837-87e5df00-76d6-11eb-818a-ea5a7422da4a.png">

**Comment by Skeli789** [comment]
Fixed
