### ISSUE TITLE
MEDIUM: Reset Password Card Overflows Device Window

### ISSUE THREAD

**Issue by SEsseltine** [behdadkha/ToeFX#81]
### Bug Description
The reset password card overflows the viewport of the device on mobile devices.

**Severity:** MEDIUM

### Recreation Steps
On a mobile device:
1. Log in as a user
2. Navigate to the Reset Password page

### Environment
**Browser:** Google Chrome

### Expected Behaviour
The Reset Password card should fit within the device's viewport.

### Actual Behaviour 
The Reset Password card overflows the device's viewport causing odd scrolling.

### Supporting Images
![image](https://user-images.githubusercontent.com/16650214/110253040-38b17100-7f56-11eb-8c21-affeeec8ba0b.png)

**Comment by Skeli789** [comment]
Fixed
