### ISSUE TITLE
HIGH: Unable to Upload Images on Mobile Devices

### ISSUE THREAD

**Issue by SEsseltine** [behdadkha/ToeFX#82]
### Bug Description
The Upload button is not present when on mobile devices

**Severity:** HIGH

### Recreation Steps
On a mobile device:
1. Log in as a valid-user

### Environment
**Browser:** Google Chrome

### Expected Behaviour
The upload button should be visible and clickable

### Actual Behaviour 
The upload button is not visible

### Supporting Images
![image](https://user-images.githubusercontent.com/16650214/110253279-75ca3300-7f57-11eb-891d-cf446cad1cab.png)

**Comment by Skeli789** [comment]
Fixed
