### ISSUE TITLE
LOW: Foot Interface Overlaps and Hard to Click on Mobile

### ISSUE THREAD

**Issue by SEsseltine** [behdadkha/ToeFX#83]
### Bug Description
The foot interface for filtering the graph overflows the screen and overlaps on itself making it hard to use.

**Severity:** LOW

### Recreation Steps
On a mobile device
1. Log in as a valid-user

### Environment
**Browser:** Google Chrome

### Expected Behaviour
The foot interface should scale and reposition maintaining shape and functionality.

### Actual Behaviour 
The foot interface collapses on itself and overflows the device display.

### Supporting Images
![image](https://user-images.githubusercontent.com/16650214/110253365-e96c4000-7f57-11eb-87bb-27b2e1fc7e0a.png)

**Comment by Skeli789** [comment]
Fixed
