### ISSUE TITLE
LOW: My Account Page Over-Scrollable on Mobile Devices

### ISSUE THREAD

**Issue by SEsseltine** [behdadkha/ToeFX#84]
### Bug Description
The user can scroll past the end of the content on mobile devices on the My Account page if images have been uploaded

**Severity:** HIGH

### Recreation Steps
On a mobile device logged-in as a user with active images:
1. Navigate to the My Account page
2. Scroll Down

### Environment
**Browser:** Google Chrome

### Expected Behaviour
Scrolling should not scroll past the end of the content

### Actual Behaviour 
User can scroll into contentless whitespace

### Supporting Images
![image](https://user-images.githubusercontent.com/16650214/110253778-21748280-7f5a-11eb-8e02-9ec0c43b20ad.png)

**Comment by Skeli789** [comment]
Fixed
