### ISSUE TITLE
LOW: Password Validation not Highlighting Red on Error

### ISSUE THREAD

**Issue by SEsseltine** [behdadkha/ToeFX#86]
### Bug Description
The password validation does not always highlight the field red when an error is present

**Severity:** LOW

### Recreation Steps

1. Navigate to the sign-up page
2. Enter a sample email
3. Enter a single character password
4. Re-enter the same character in the confirm password field
5. Enter a name
6. Enter an age
7. Click the Create Account button

### Environment
**Browser:** Google Chrome

### Expected Behaviour
The Password and Confirm Password Fields should be highlighted red

### Actual Behaviour 
No change is present in the Password and Confirm Password Fields

### Supporting Images
![image](https://user-images.githubusercontent.com/16650214/110254138-d2c7e800-7f5b-11eb-9d1f-ddaa9ad47091.png)

**Comment by Skeli789** [comment]
Fixed
