### ISSUE TITLE
Creating an account sometimes fails and reports email in use even if the email is new

### ISSUE THREAD

**Issue by Gabriel-Gebril** [behdadkha/ToeFX#87]
If the frontend server stops for some reason and you try to make an account after that it always say the email is in use.
Environment: 
Windows, FireFox
Steps to Reproduce:
- Sign up using an arbitrary email
- Stop the frontend server
- Forget the password to the account you create
- Try to make a new account
- Notice how no matter what email you use you aren't allowed to make a new account

**Comment by Skeli789** [comment]
Fixed
