### ISSUE TITLE
Large delay on red highlight on firefox

### ISSUE THREAD

**Issue by Gabriel-Gebril** [behdadkha/ToeFX#88]
When signing up using firefox if any of the signup fields are invalid it can take up a full minute to receive feedback

Environment:
Windows, Firefox

Steps to reproduce:
- Go to sign up page on firefox
- Fill in all fields except valid except for one invalid field of your choice
- Click "sign up"
- Notice that it takes a long time to highlight an error

**Comment by behdadkha** [comment]
Not an issue with the app, docker probably took up a big part of your memory, slowing down the frontend server.
