### ISSUE TITLE
LOW - Login/Register Page - Email Address form label should be capitalized (currently "Email address", should be "Email Address")

### ISSUE THREAD

**Issue by OneCodeMan** [behdadkha/ToeFX#9]
# Summary
On the login page and register page, all form labels with more than one word (full name, confirm password) are capitalized, except for email address. This seems to break consistency.

# Environment
Platform: Desktop
OS: Mac
Browser: Chrome

# Steps to Reproduce
1. Go to `http://localhost:3000/login` without being logged in.
2. Observe "Email address" as form field label.
<img width="439" alt="Bildschirmfoto 2021-02-24 um 19 39 18" src="https://user-images.githubusercontent.com/15069287/109085881-83bac100-76d8-11eb-9a35-2a121c7686f3.png">

3. Repeat steps 1 and 2 for the URL` http://localhost:3000/register`
<img width="515" alt="Bildschirmfoto 2021-02-24 um 19 33 40" src="https://user-images.githubusercontent.com/15069287/109085860-77ceff00-76d8-11eb-9f8f-f616c56e782d.png">

# Notes
Notice how the other form field labels with more than one word are capitalized
<img width="513" alt="Bildschirmfoto 2021-02-24 um 19 39 29" src="https://user-images.githubusercontent.com/15069287/109085924-9cc37200-76d8-11eb-8e09-b36ae90e4ed9.png">

**Comment by Skeli789** [comment]
Fixed
