### ISSUE TITLE
No sign to remind the user when the caps-lock is on

### ISSUE THREAD

**Issue by yangy113** [behdadkha/ToeFX#91]
![image](https://user-images.githubusercontent.com/70185196/110303783-c44dff00-8035-11eb-9477-160631b8e053.png)

When the caps-lock of my machine is on, this is the screenshot when I select the password bar. There is no sign to show the caps-lock is on. This is easy to make the user enter wrong password. A reminder is needed here, I think.

**Comment by Skeli789** [comment]
Most applications these days don't give the user a notification when their CAPS lock is on, so we probably won't end up implementing this either.

**Comment by behdadkha** [comment]
Not an issue!
