### ISSUE TITLE
import fastai.callbacks.hooks

### ISSUE THREAD

**Issue by gattia** [behdadkha/ToeFX#93]
Looks like the latest versions of `fastai` break FungalCoverage.py

e.g., `fastai.callbacks.hooks` doesn't exist. 

Suggest saving a `requirements.txt` from miniconda or from pip and using it install the appropriate dependencies of all libraries.

**Comment by Skeli789** [comment]
Fixed in deecfe24b0eaef84154abb224a3b9e65e1ce3c6c.
